version: '3.3'

services:
  # nginx
  nginx:
    image: nginx
    volumes:
      - ./nginxdocker/:/usr/share/nginx/html/
    ports:
      - "8080:80"
  # mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
